apiVersion: v1
kind: Service
metadata:
  name: {{ include "yolov8.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yolov8.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "yolov8.frontend.selectorLabels" . | nindent 4 }}
