{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "yolov8.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yolov8.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "yolov8.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "yolov8.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yolov8.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "yolov8.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
